name: flutter_firebase_app
description: Flutter Firebase App with Edubot
publish_to: 'none'

environment:
  sdk: ^3.9.0

# This is a workspace configuration file
# The actual Flutter app is located in the edubot/ directory
